clc ; 
close all; 
clear all ;
original_image = imread('lenna.png') ; 
infor_image    = imfinfo('lenna.png') ; 
H = infor_image.Height ;
W = infor_image.Width; 
figure(3) ; 
imshow(uint8(original_image)) ; 
filtered_image = mean_filter(original_image) ; 
matlab_result  = filtered_image' ; 
matlab_result  = matlab_result(:) ; 
verilog_result = uint8(importdata('../py/out_y.txt')); 
filtered_ver_image = reshape(verilog_result,H,W) ; 
filtered_ver_image = filtered_ver_image';
diff = int32(matlab_result) - int32(verilog_result) ; 
figure(1) ; 
subplot(1,2,1) ; imshow(filtered_image) ; title('Matlab resulted image') ; 
subplot(1,2,2) ; imshow(filtered_ver_image) ; title('Verilog resulted image') ; 
figure(2) ; 
stem(diff) ; title('difference between matlab result and verilog result') ; 